dependencies:
  - smartcontractkit/chainlink-brownie-contracts@1.1.1
  - OpenZeppelin/openzeppelin-contracts@3.4.0
  - Uniswap/v2-core@1.0.1
compiler:
  solc:
    remappings:
      - '@chainlink=smartcontractkit/chainlink-brownie-contracts@1.1.1'
      - '@openzeppelin=OpenZeppelin/openzeppelin-contracts@3.4.0'
dotenv: .env
networks:
  default: development
  mainnet-fork:
    verify: False
    cmd_settings:
      unlimited_contract_size: True
      accounts: 10
      default_balance: '100 ether'
  development:
    persist: false
    cmd_settings:
      default_balance: '10000 ether'
wallets:
  from_key: ${PRIVATE_KEY}